services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
      - "4571:4571" # Api gateway ports
    volumes:
      - mysql-data:/var/lib/mysql

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: sns,sqs,lambda,apigateway
      DEFAULT_REGION: sa-east-1
    ports:
      - "4566:4566"
      - "4575:4575"
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

volumes:
  mysql-data:
  localstack-data:
